// DO NOT EDIT THIS FILE
// draw mushroom in various stages while it
// is growing.
// AUTHOR: pongsak.suvanpong@mq.edu.au
// Image Cradit : Risa Suvanpong

final int nState = 9;
PImage[] mushroomStages = new PImage[nState];
final int spriteWidth = 100;
final int spriteHeight = 100;
final String imagePath = "mushroomgrid.png";
boolean hasBeenInit = false;

void initMushroomImages()
{
  PImage p = loadImage(imagePath);
  int y = 100;
  for(int i = 0; i < mushroomStages.length; i++)
  {
    mushroomStages[i] = p.get(0, y, spriteWidth, spriteWidth);
    y = y + 100;
  }
}

void drawMushroom(float x, float y, float w, float h, int state)
{
  if(state < 0 || state > 8)
  {
    fill(255);
    rect(x, y, w, h);
  }
  else
  {
    if(!hasBeenInit)
    {
      initMushroomImages();
      hasBeenInit = true;
    }
    image(mushroomStages[state], x, y, w, h);
  }
}
